{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/42459",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/42459/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/42459/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/42459/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/42459",
  "id": 681035357,
  "node_id": "MDU6SXNzdWU2ODEwMzUzNTc=",
  "number": 42459,
  "title": "Accuracy is lost after save/load",
  "user": {
    "login": "ThatDockerUser",
    "id": 66676720,
    "node_id": "MDQ6VXNlcjY2Njc2NzIw",
    "avatar_url": "https://avatars.githubusercontent.com/u/66676720?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ThatDockerUser",
    "html_url": "https://github.com/ThatDockerUser",
    "followers_url": "https://api.github.com/users/ThatDockerUser/followers",
    "following_url": "https://api.github.com/users/ThatDockerUser/following{/other_user}",
    "gists_url": "https://api.github.com/users/ThatDockerUser/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ThatDockerUser/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ThatDockerUser/subscriptions",
    "organizations_url": "https://api.github.com/users/ThatDockerUser/orgs",
    "repos_url": "https://api.github.com/users/ThatDockerUser/repos",
    "events_url": "https://api.github.com/users/ThatDockerUser/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ThatDockerUser/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 386191887,
      "node_id": "MDU6TGFiZWwzODYxOTE4ODc=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20response",
      "name": "stat:awaiting response",
      "color": "f4b400",
      "default": false,
      "description": "Status  - Awaiting response from author"
    },
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 474725938,
      "node_id": "MDU6TGFiZWw0NzQ3MjU5Mzg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stalled",
      "name": "stalled",
      "color": "d4c5f9",
      "default": false,
      "description": "stalled"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1946362326,
      "node_id": "MDU6TGFiZWwxOTQ2MzYyMzI2",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.3",
      "name": "TF 2.3",
      "color": "1d76db",
      "default": false,
      "description": "Issues related to TF 2.3"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "jvishnuvardhan",
    "id": 46058173,
    "node_id": "MDQ6VXNlcjQ2MDU4MTcz",
    "avatar_url": "https://avatars.githubusercontent.com/u/46058173?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jvishnuvardhan",
    "html_url": "https://github.com/jvishnuvardhan",
    "followers_url": "https://api.github.com/users/jvishnuvardhan/followers",
    "following_url": "https://api.github.com/users/jvishnuvardhan/following{/other_user}",
    "gists_url": "https://api.github.com/users/jvishnuvardhan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jvishnuvardhan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jvishnuvardhan/subscriptions",
    "organizations_url": "https://api.github.com/users/jvishnuvardhan/orgs",
    "repos_url": "https://api.github.com/users/jvishnuvardhan/repos",
    "events_url": "https://api.github.com/users/jvishnuvardhan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jvishnuvardhan/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "jvishnuvardhan",
      "id": 46058173,
      "node_id": "MDQ6VXNlcjQ2MDU4MTcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/46058173?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jvishnuvardhan",
      "html_url": "https://github.com/jvishnuvardhan",
      "followers_url": "https://api.github.com/users/jvishnuvardhan/followers",
      "following_url": "https://api.github.com/users/jvishnuvardhan/following{/other_user}",
      "gists_url": "https://api.github.com/users/jvishnuvardhan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jvishnuvardhan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jvishnuvardhan/subscriptions",
      "organizations_url": "https://api.github.com/users/jvishnuvardhan/orgs",
      "repos_url": "https://api.github.com/users/jvishnuvardhan/repos",
      "events_url": "https://api.github.com/users/jvishnuvardhan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jvishnuvardhan/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 9,
  "created_at": "2020-08-18T13:18:44Z",
  "updated_at": "2020-10-20T16:28:27Z",
  "closed_at": "2020-09-03T21:23:53Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): See below.\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, 1909\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -\r\n- TensorFlow installed from (source or binary): pip\r\n- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0\r\n- Python version: 3.7.7\r\n- Bazel version (if compiling from source): -\r\n- GCC/Compiler version (if compiling from source): -\r\n- CUDA/cuDNN version: -\r\n- GPU model and memory: Not relevant.\r\n\r\n**Describe the current behavior**\r\nWhen saving a pre-trained model and loading it again, the accuracy drops to its default value. Minimal example:\r\n```\r\nimport tensorflow as tf\r\n\r\nmodel = tf.keras.models.Sequential()\r\nmodel.add(tf.keras.layers.Dense(units=2, activation='softmax', name='output'))\r\nmodel.compile(optimizer=tf.keras.optimizers.Adam(lr=10),\r\n              loss='sparse_categorical_crossentropy',\r\n              metrics=['accuracy'])\r\ndummy_data_x = [[0, 0],\r\n                [1, 0],\r\n                [0, 1],\r\n                [1, 1]]\r\ndummy_data_y = [0, 1, 0, 1]\r\nprint(model.evaluate(x=dummy_data_x, y=dummy_data_y))\r\nmodel.fit(x=dummy_data_x, y=dummy_data_y, epochs=10)\r\nprint(model.evaluate(x=dummy_data_x, y=dummy_data_y))\r\nmodel.save('test_model')\r\nmodel = tf.keras.models.load_model('test_model')\r\nprint(model.evaluate(x=dummy_data_x, y=dummy_data_y))\r\n```\r\nThe model is extremely simple (read: bad/useless) for comparison's sake. Before training it, the evaluation results in:\r\n```\r\n1/1 [==============================] - 0s 0s/step - loss: 0.9013 - accuracy: 0.5000\r\n[0.9013183116912842, 0.5]\r\n```\r\nThe loss is obviously random at first, but crucially the accuracy is 50% because it guesses 0 every time. After training, it evaluates to:\r\n```\r\n1/1 [==============================] - 0s 0s/step - loss: 0.0000e+00 - accuracy: 1.0000\r\n[0.0, 1.0]\r\n```\r\nThe loss dropped to zero and the model can perfectly interpret the data. Now I save the model to the disk and immediately load it from the same location. When I now evaluate it, I get:\r\n```\r\n1/1 [==============================] - 0s 1000us/step - loss: 0.0000e+00 - accuracy: 0.5000\r\n[0.0, 0.5]\r\n```\r\nEven though the model has the same structure, weights, and loss, and all four example inputs are evaluated correctly, TensorFlow says the accuracy is 50%, which is not true.\r\n\r\n**Describe the expected behavior**\r\nThe accuracy should remain the same when loading a previously trained and saved model.\r\n\r\n**Standalone code to reproduce the issue**\r\nSee above.\r\n\r\n**Other info / logs**\r\nSee above.\r\n",
  "closed_by": {
    "login": "goldiegadde",
    "id": 43185254,
    "node_id": "MDQ6VXNlcjQzMTg1MjU0",
    "avatar_url": "https://avatars.githubusercontent.com/u/43185254?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/goldiegadde",
    "html_url": "https://github.com/goldiegadde",
    "followers_url": "https://api.github.com/users/goldiegadde/followers",
    "following_url": "https://api.github.com/users/goldiegadde/following{/other_user}",
    "gists_url": "https://api.github.com/users/goldiegadde/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/goldiegadde/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/goldiegadde/subscriptions",
    "organizations_url": "https://api.github.com/users/goldiegadde/orgs",
    "repos_url": "https://api.github.com/users/goldiegadde/repos",
    "events_url": "https://api.github.com/users/goldiegadde/events{/privacy}",
    "received_events_url": "https://api.github.com/users/goldiegadde/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/42459/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/42459/timeline",
  "performed_via_github_app": null
}
