{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38938",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38938/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38938/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38938/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/38938",
  "id": 607340408,
  "node_id": "MDU6SXNzdWU2MDczNDA0MDg=",
  "number": 38938,
  "title": "Keras: model.fit_generator or model.fit not working properly",
  "user": {
    "login": "sanidhyamangal",
    "id": 23209383,
    "node_id": "MDQ6VXNlcjIzMjA5Mzgz",
    "avatar_url": "https://avatars.githubusercontent.com/u/23209383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sanidhyamangal",
    "html_url": "https://github.com/sanidhyamangal",
    "followers_url": "https://api.github.com/users/sanidhyamangal/followers",
    "following_url": "https://api.github.com/users/sanidhyamangal/following{/other_user}",
    "gists_url": "https://api.github.com/users/sanidhyamangal/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sanidhyamangal/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sanidhyamangal/subscriptions",
    "organizations_url": "https://api.github.com/users/sanidhyamangal/orgs",
    "repos_url": "https://api.github.com/users/sanidhyamangal/repos",
    "events_url": "https://api.github.com/users/sanidhyamangal/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sanidhyamangal/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1315098405,
      "node_id": "MDU6TGFiZWwxMzE1MDk4NDA1",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/regression%20issue",
      "name": "regression issue",
      "color": "50bcc4",
      "default": false,
      "description": "To spot regression issues in TF 2.0"
    },
    {
      "id": 1903591931,
      "node_id": "MDU6TGFiZWwxOTAzNTkxOTMx",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.2",
      "name": "TF 2.2",
      "color": "0052cc",
      "default": false,
      "description": "Issues related to TF 2.2"
    },
    {
      "id": 2046763290,
      "node_id": "MDU6TGFiZWwyMDQ2NzYzMjkw",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/Fixed%20in%20Nightly",
      "name": "Fixed in Nightly",
      "color": "5ecc37",
      "default": false,
      "description": "Issues that are resolved in nightly version"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "omalleyt12",
      "id": 29100818,
      "node_id": "MDQ6VXNlcjI5MTAwODE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/omalleyt12",
      "html_url": "https://github.com/omalleyt12",
      "followers_url": "https://api.github.com/users/omalleyt12/followers",
      "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
      "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
      "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
      "repos_url": "https://api.github.com/users/omalleyt12/repos",
      "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
      "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "ravikyram",
      "id": 51902062,
      "node_id": "MDQ6VXNlcjUxOTAyMDYy",
      "avatar_url": "https://avatars.githubusercontent.com/u/51902062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ravikyram",
      "html_url": "https://github.com/ravikyram",
      "followers_url": "https://api.github.com/users/ravikyram/followers",
      "following_url": "https://api.github.com/users/ravikyram/following{/other_user}",
      "gists_url": "https://api.github.com/users/ravikyram/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ravikyram/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ravikyram/subscriptions",
      "organizations_url": "https://api.github.com/users/ravikyram/orgs",
      "repos_url": "https://api.github.com/users/ravikyram/repos",
      "events_url": "https://api.github.com/users/ravikyram/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ravikyram/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 10,
  "created_at": "2020-04-27T08:22:25Z",
  "updated_at": "2020-06-18T09:35:54Z",
  "closed_at": "2020-06-18T09:29:33Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes\r\n- OS Platform and Distribution: Ubuntu 18.04.3 LTS\r\n- TensorFlow installed from (source or binary): binary\r\n- TensorFlow version (use command below): 2.2.0-rc3\r\n- Python version: 3.6.9\r\n- CUDA/cuDNN version: (colab)\r\n- GPU model and memory: (colab)\r\n\r\n**Describe the current behavior**\r\nWhile using ```model.fit``` or ```model.fit_generator``` the sub iterations in epoch shows unknown number of iterations which is goes on despite surpassing the batch size.\r\n\r\n**Describe the expected behavior**\r\nWhile using ```model.fit``` or ```model.fit_generator``` the sub iterations in epoch must be definite.\r\n\r\n**Standalone code to reproduce the issue**\r\nProvide a reproducible test case that is the bare minimum necessary to generate\r\nthe problem. If possible, please share a link to [Colab](https://colab.research.google.com/drive/1dWbszUUjRagXyJUUqjdsM1yXtaAmKc23).\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\ndiagnose the problem. If including tracebacks, please include the full\r\ntraceback. Large logs and files should be attached.\r\n\r\n```shell\r\nWARNING:tensorflow:From <ipython-input-23-2da3481afcb0>:1: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.\r\nInstructions for updating:\r\nPlease use Model.fit, which supports generators.\r\nEpoch 1/20\r\n     13/Unknown - 20s 2s/step - loss: 1.0732 - accuracy: 0.2602\r\n```",
  "closed_by": {
    "login": "sanidhyamangal",
    "id": 23209383,
    "node_id": "MDQ6VXNlcjIzMjA5Mzgz",
    "avatar_url": "https://avatars.githubusercontent.com/u/23209383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sanidhyamangal",
    "html_url": "https://github.com/sanidhyamangal",
    "followers_url": "https://api.github.com/users/sanidhyamangal/followers",
    "following_url": "https://api.github.com/users/sanidhyamangal/following{/other_user}",
    "gists_url": "https://api.github.com/users/sanidhyamangal/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sanidhyamangal/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sanidhyamangal/subscriptions",
    "organizations_url": "https://api.github.com/users/sanidhyamangal/orgs",
    "repos_url": "https://api.github.com/users/sanidhyamangal/repos",
    "events_url": "https://api.github.com/users/sanidhyamangal/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sanidhyamangal/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38938/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/38938/timeline",
  "performed_via_github_app": null
}
