{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/36668",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/36668/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/36668/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/36668/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/36668",
  "id": 563364176,
  "node_id": "MDU6SXNzdWU1NjMzNjQxNzY=",
  "number": 36668,
  "title": "TF 1.15.2: Metrics created in custom layer (self.add_metric) producing wrong output",
  "user": {
    "login": "kurka",
    "id": 585058,
    "node_id": "MDQ6VXNlcjU4NTA1OA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/585058?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kurka",
    "html_url": "https://github.com/kurka",
    "followers_url": "https://api.github.com/users/kurka/followers",
    "following_url": "https://api.github.com/users/kurka/following{/other_user}",
    "gists_url": "https://api.github.com/users/kurka/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kurka/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kurka/subscriptions",
    "organizations_url": "https://api.github.com/users/kurka/orgs",
    "repos_url": "https://api.github.com/users/kurka/repos",
    "events_url": "https://api.github.com/users/kurka/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kurka/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 404586594,
      "node_id": "MDU6TGFiZWw0MDQ1ODY1OTQ=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20tensorflower",
      "name": "stat:awaiting tensorflower",
      "color": "f4b400",
      "default": false,
      "description": "Status  - Awaiting response from tensorflower"
    },
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1548890241,
      "node_id": "MDU6TGFiZWwxNTQ4ODkwMjQx",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%201.15",
      "name": "TF 1.15",
      "color": "e99695",
      "default": false,
      "description": "for issues seen on TF 1.15"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "omalleyt12",
      "id": 29100818,
      "node_id": "MDQ6VXNlcjI5MTAwODE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/omalleyt12",
      "html_url": "https://github.com/omalleyt12",
      "followers_url": "https://api.github.com/users/omalleyt12/followers",
      "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
      "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
      "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
      "repos_url": "https://api.github.com/users/omalleyt12/repos",
      "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
      "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2020-02-11T17:30:40Z",
  "updated_at": "2020-02-28T20:27:17Z",
  "closed_at": "2020-02-28T20:27:15Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "(this seems to be the same issue as #32144, but for tf 1.15)\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04\r\n- TensorFlow installed from (source or binary): binary\r\n- TensorFlow version (use command below): 1.15.2\r\n- Python version: 3.6.9\r\n- CUDA/cuDNN version: 10.1\r\n- GPU model and memory: GeForce GTX 1080Ti\r\n\r\n\r\n**Describe the current behavior**\r\n\r\nWhen creating a custom model class (inheriting from `tf.keras.Model`), with a custom layer class (tf.keras.layers.Layer) as attribute, and trying to define metrics (using `self.add_metric()`) in both the outer class and the inner layer, the metrics outputs seem to be swapped (keys and values do not match) when training with `model.fit`.\r\n\r\n**Describe the expected behavior**\r\n\r\nMetrics names and values should match.\r\nThis seems to be an issue only of tf 1. Did not observe this in tf 2.1.\r\n\r\n**Code to reproduce the issue**\r\n```python\r\nimport tensorflow as tf\r\nfrom tensorflow.keras import layers\r\n\r\nclass InnerLayer(layers.Layer):\r\n\r\n    def __init__(self):\r\n        super(InnerLayer, self).__init__()\r\n\r\n    def call(self, inputs):\r\n        # Should always print 1.0\r\n        self.add_metric(tf.constant(1.0), aggregation='mean',\r\n                        name='should_be_1')\r\n        return inputs\r\n\r\n\r\nclass OuterModel(tf.keras.Model):\r\n    def __init__(self):\r\n        super(OuterModel, self).__init__()\r\n        self.inner = InnerLayer()\r\n\r\n    def call(self, inputs):\r\n        # Should always print 2.0\r\n        self.add_metric(tf.constant(2.0), aggregation='mean',\r\n                        name='should_be_2')\r\n        return self.inner(inputs)\r\n\r\n\r\nmodel = OuterModel()\r\nmodel.compile('adam', loss='mse')\r\ndataset = tf.random.normal((100, 5))\r\nmodel.fit(dataset, dataset, epochs=10, steps_per_epoch=100, verbose=2)\r\n```\r\nOutput (with bug):\r\n\r\n```\r\nEpoch 1/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 2/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 3/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 4/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 5/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 6/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 7/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 8/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 9/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\nEpoch 10/10\r\n100/100 - 0s - loss: 0.0000e+00 - should_be_1: 2.0000 - should_be_2: 1.0000\r\n```",
  "closed_by": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/36668/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/36668/timeline",
  "performed_via_github_app": null
}
